[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  included_files = ["netlify/functions/**/*"]

  [functions.chat]
    description = "AI-powered HR assistant that answers questions about company policies and benefits using the Sixty Two handbook data"

  [functions.hello]
    description = "Simple health check endpoint that confirms the serverless functions are working"

[build.environment]
  NODE_VERSION = "18"

[dev]
  targetPort = 5173
  functionsPort = 8888
  port = 8888
  framework = "vite"